[#p7,reftext=P.7]
=== (P.7) Requirements process and report

ifdef::env-draft[]
TIP: _Initially, description of what the requirements process will be; later, report on its steps. It starts out as a plan for conducting the requirements elicitation process, but is meant to be updated as part of that process so that it includes the key lessons of elicitation._  <<BM22>>
endif::[]

The requirements elicitation process will likely be done using open-ended surveys for large populations and open interviews for smaller, more technical stakeholders, since they offer a greater amount of possible responses compared to open interviews, but still allow for the user to asnwer in a way that they feel is the most correct, as opposed to forcing arbitrary choices on them. If the stakeholder is a non-human entity, they likely have documentation for which document analysis will be our primary elicitation method.

*   Surveys with some open-ended answer options should be used when eliciting requirements from our casual gamer stakeholders. With this stakeholder, it's important to remember that everyone games in a different way, and what might be normal for one person might not even be considered by another. Closed-form questions will not accurately capture the requirements that we need from this stakeholder. 

*   Open interviews should be used when eliciting requirements from developers. Unlike casual gamers, developers can provide highly technical and design-oriented feedback, often rooted in best practices, prior experience, and knowledge of what makes games successful. Open interviews allow for in-depth conversations where specific points can be expanded on, and where follow-up questions can be asked if developers identify potential risks, implementation challenges, or opportunities for improvement. This approach ensures that critical insights aren't lost in rigid survey structures and instead are captured through detailed discussion.

*   Document analysis is the primary requirement elicitation method for Steam, as they are an established marketplace and regulator of content, they have certain standards which they have documented. Steam is generally not represented by just a few individuals so our normal requirements elicitation process does not work, but if after the document analysis we still have questions, asking questions to their support is the way to elicit requirements.

*   Document analysis is the primary elicitation method for Government Organizations, as they are literally required to have their standards in writing. This will include studying regional legislation in places where we plan to make the game available, or other rating standards. In cases where regulation is unclear, formal correspondance or consultations with legal experts or compliance officers may be necessary
{emptysec}


