[#s2,reftext=S.2]
=== (S.2) Functionality

==== (S.2.1) Save Data Manager

===== Functional Requirements

1. **Create save data:** Upon launching the game, if there is no save file found, a new save file will be generated on the user's computer file system. (F211)
2. **Restore from save data:** Upon launching the game, if there is an existing save file found, then that file will be loaded to restore the player's progress from their previous session. (F212)
3. **Auto-save:** Each time the player completes a puzzle and progresses to the next scene, the game will automatically save their progress, updating the save file. (F213)
4. **Reset puzzle:** The player has the option to reset a puzzle room to start over, in case they got lost or softlocked. (F214)

===== Non-Functional Requirements

1. **Data privacy:** Only data related to game progression is saved to the save file; personal information is not collected. (NF211)
2. **Compression:** The save file will be in a compressed, binary format to minimize the file space required to store it on the player's computer. (NF212)

==== (S.2.2) Game Objects & Environment

===== Functional Requirements

1. **Destructible environment:** The system shall simulate the usage of destructive tools, which, when interacting with terrain designated as destructible, will decompose the terrain game object into several smaller blocks of terrain. The sum of the areas of the decomposed blocks is roughly equal to the area of the terrain that was removed. The system shall correctly identify and produce logical debris amount, colour and shape, based on the attributes of the original object. (F221)
2. **Slime mold simulation:** The system shall simulate an organism whose behaviour is modelled by the slime mold algorithm, which shall be nondeterministic but largely predictable and manipulable, based on attraction or repulsion to/from water, light and heat. (F222)
3. **Puzzle progression:** The system shall contain environmental puzzles with a definite start and end which the player can traverse through by solving the puzzle; each puzzle requires the player to assist the slime mold organism in order to reveal a path forward. (F223)

===== Non-Functional Requirements

1. **Game difficulty and length:** The puzzles in the game shall be presented in chunks (referred to as "levels"), such that each level can be completed within a reasonable time frame (an estimated 15-20 minutes). (NF221)
2. **Replayability and randomness:** The nondeterministic behaviour of the slime mold organism and the decomposed terrain generation shall create variance in a way that improves replayability of the game, while the puzzles themselves can still be solved regardless of the random elements of game behaviour. (NF222)

==== (S.2.3) Safety & Security

===== Non-Functional Requirements

1. **Stability:** The system shall experience crashes no more frequently than once every two hours on average. (NF231)
2. **Crash logs:** Should a crash occur, the system shall display as much detail about the crash as possible in a pop-up window, for diagnostic purposes. Developer contact information will be provided for the purpose of bug reporting. (NF232)
3. **Privileges:** The system shall be able to run without requiring administrator privileges. (NF233)
4. **Software vulnerabilities:**  Any Unity security vulnerabilities shall be patched in a timely fashion and distributed in a software update. (NF234)
