[#s4,reftext=S.4]
=== (S.4) Detailed usage scenarios

Destructable Environment
• Use Case: S2-FLD-1
• Primary Actor: Player
• Precondition: Has access to reachable game object that is destructible
• Trigger: Player strikes through the object with their tool and causes damage above certain threshold
Main Success Scenario
Player aims tool at game object or terrain
Object/s in the aim path are highlighted of the chunk that will be broken off
Player clicks left mouse button and the strike is executed
The chunk is broken off and breaks down further into small debris to be manipulated and/or traversed by player
Secondary Scenario
The object or terrain the player carves off contains water and water is released
Water accumulates at a point which can be utilized by the slime mold as a destination point to traverse to

Success PostCondition
Player is able to traverse over obstacles by breaking up game objects and debris  and/or guide water flow to unlock pathways and/or guide slime mold


Organic Dynamic Paths(slime mold)
• Use Case: S2-FLD-2
• Primary Actor: Player
• Precondition: Has existing slime mold sources in the game
• Trigger: There is flowing source of water either released and/or guided by player
Main Success Scenario
Player releases water source to the right location either by striking object or solving a level puzzle
Slime mold finds a creative path from its original location to water source
Player walks over top of the organic pathway in order to traverse previously untraversable distances
Secondary Scenario
N/A

Success PostCondition
Player is able to traverse over obstacles by breaking up game objects and debris  and/or guide water flow to unlock pathways and/or guide slime mold

