[#g7,reftext=G.7]
=== (G.7) Stakeholders and requirements sources

Direct Stakeholders
Casual Gamers: Gamers who play games on a non competitive capacity and as such value the experience rather than solely a challenge. Having already been familiar with similar games, basic game controls should be intuitive to them

Developers: The prospective developers of this game should have baseline knowledge of games and gaming are anticipated to be somewhat inexperienced with game development. However they are able to leverage their preexisting knowledge to understand what is fun and entertaining in a game from an user perspective as well as conduct internal debugging - potentially expand with external company developers. 

Indirect Stakeholders
Steam: The shopfront and regulator of the sale of our game. Its algorithms and policies can determine the success and failure of our game. All aspects in the game are required to be complaint with Steam policies

Government Organizations: Different government set policies on what is allowed and not allowed in games
